
ERROR:root:Error: 
Traceback (most recent call last):
  File "process_monitor.py", line 31, in <module>
    processes = ProcessService.getAll(excludeProcess, minUID=1000)
  File "/home/tung/Desktop/ktlt/utils.py", line 96, in getAll
    p = Process(proc)
  File "/home/tung/Desktop/ktlt/utils.py", line 38, in __init__
    self.__getProcessResources(process)
  File "/home/tung/Desktop/ktlt/utils.py", line 42, in __getProcessResources
    = process.io_counters()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 787, in io_counters
    return self._proc.io_counters()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1322, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=1497, name='(sd-pam)')
ERROR:root:Error: 
Traceback (most recent call last):
  File "process_monitor.py", line 40, in <module>
    jsampleRepo.add(jSample(proc))
  File "/home/tung/Desktop/ktlt/utils.py", line 331, in add
    self.db.commit()
KeyboardInterrupt
